INSERT INTO modele (manufacturier, modeleNom, winter, allWeather, rft, typeModel, pictureLink) VALUES ("BRIDGESTONE","TURANZA EL42 RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_EL42_RFT.jpg"),
("FIRESTONE","CHAMPION FUEL FIGHTER","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_CHAMPION_FUEL_FIGHTER.jpg"),
("FIRESTONE","FIREHAWK GT PURSUIT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_FIREHAWK_GT_PURSUIT.jpg"),
("BRIDGESTONE","DUELER H/P SPORT AS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HP_SPORT_AS.jpg"),
("BRIDGESTONE","ECOPIA EP422","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_ECOPIA_EP422.jpg"),
("BRIDGESTONE","ECOPIA EP422 PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_ECOPIA_EP422_PLUS.jpg"),
("FIRESTONE","DESTINATION LE2","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_DESTINATION_LE2.jpg"),
("BRIDGESTONE","POTENZA RE97AS RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE97AS_RFT.jpg"),
("BRIDGESTONE","TURANZA EL400-02 RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_EL400_02_RFT.jpg"),
("FIRESTONE","AFFINITY TOURING S4 FF","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_AFFINITY_TOURING_S4_FF.jpg"),
("BRIDGESTONE","POTENZA S001 RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_S_001_I_RFT.jpg"),
("MICHELIN","LATITUDE X-ICE XI2","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_X_ICE_XI2.jpg"),
("BRIDGESTONE","POTENZA RE97AS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE97AS.jpg"),
("BRIDGESTONE","DUELER H/L ALENZA PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HL_ALENZA_PLUS.jpg"),
("BRIDGESTONE","BLIZZAK LM-32 RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_LM_32_RFT.jpg"),
("BRIDGESTONE","TURANZA EL400-02 ECOPIA","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_EL400_02_RFT.jpg"),
("BRIDGESTONE","TURANZA EL400-02","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_EL400_02_RFT.jpg"),
("BRIDGESTONE","POTENZA RE050A RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE050A_I_RFT.jpg"),
("BRIDGESTONE","POTENZA RE050A","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE050A.jpg"),
("BRIDGESTONE","DUELER H/L 400","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HL400.jpg"),
("BRIDGESTONE","BLIZZAK LM-80 RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_LM_80_RFT.jpg"),
("MICHELIN","PILOT SPORT CUP 2","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_CUP_2.jpg"),
("BRIDGESTONE","DUELER H/L ALENZA","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HL_ALENZA.jpg"),
("BRIDGESTONE","DUELER A/T RH-S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_AT_RH_S.jpg"),
("BRIDGESTONE","DUELER H/P SPORT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HP_SPORT.jpg"),
("BRIDGESTONE","POTENZA RE-11","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE_11.jpg"),
("BRIDGESTONE","ECOPIA EP150","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_ECOPIA_EP150.jpg"),
("BRIDGESTONE","TURANZA ER33","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_ER33.jpg"),
("FIRESTONE","FIREHAWK GT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_FIREHAWK_GT.jpg"),
("BRIDGESTONE","POTENZA S04 PP","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_S04PP.jpg"),
("BRIDGESTONE","DRIVEGUARD RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DRIVEGUARD_RFT.jpg"),
("FIRESTONE","FR710","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_FR710.jpg"),
("BRIDGESTONE","POTENZA S001","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_S_001_I_RFT.jpg"),
("BRIDGESTONE","POTENZA RE070R R2 RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE070R_R2_RFT.jpg"),
("MICHELIN","PILOT ALPIN PA4","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_ALPIN_PA4.jpg"),
("BRIDGESTONE","POTENZA S007","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_S007_RFT.jpg"),
("BRIDGESTONE","ECOPIA EP600","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_ECOPIA_EP600.jpg"),
("BRIDGESTONE","POTENZA S007 RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_S007_RFT.jpg"),
("FIRESTONE","FR740","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_FR740.jpg"),
("BRIDGESTONE","B380 RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_B380_RFT.jpg"),
("BRIDGESTONE","BLIZZAK LM-500","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_LM_500.jpg"),
("BRIDGESTONE","DUELER H/T D687","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HT_687.jpg"),
("BRIDGESTONE","POTENZA S001 I","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_S_001_I_RFT.jpg"),
("BRIDGESTONE","TURANZA EL470","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_EL470.jpg"),
("MICHELIN","PILOT SUPER SPORT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SUPER_SPORT.jpg"),
("BRIDGESTONE","BLIZZAK LM-32","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_LM_32.jpg"),
("FIRESTONE","FIREHAWK INDY 500","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_FIREHAWK_WIDE_OVAL_INDY_500.jpg"),
("BRIDGESTONE","DUELER H/T D684 II","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HT_684_II.jpg"),
("FIRESTONE","DESTINATION A/T","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_DESTINATION_AT.jpg"),
("BRIDGESTONE","V-STEEL RIB R265","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_V_STEEL_RIB_265.jpg"),
("FIRESTONE","TRANSFORCE HT","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_TRANSFORCE_HT.jpg"),
("BRIDGESTONE","DUELER H/L 400 RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HL400_RFT.jpg"),
("BRIDGESTONE","DUELER H/P SPORT RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HP_SPORT_RFT.jpg"),
("BRIDGESTONE","TURANZA ER33 RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_ER33_RFT.jpg"),
("BRIDGESTONE","POTENZA RE050","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE050.jpg"),
("BRIDGESTONE","DUELER A/T D693 III","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_AT_D693_II.jpg"),
("BRIDGESTONE","DUELER H/P SPORT ECOPIA","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HP_SPORT_ECOPIA.jpg"),
("FIRESTONE","TRANSFORCE AT","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_TRANSFORCE_AT.jpg"),
("BRIDGESTONE","POTENZA RE040","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE040_RFT.jpg"),
("BRIDGESTONE","ECOPIA EP20","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_ECOPIA_EP20.jpg"),
("FIRESTONE","WINTERFORCE LT","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_WINTERFORCE_LT.jpg"),
("BRIDGESTONE","DUELER H/T D840","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HT_D840.jpg"),
("UNIROYAL","LAREDO CROSS COUNTRY TOUR","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/UNIROYAL/UNIROYAL_LAREDO_CROSS_COUNTRY_TOUR.jpg"),
("BRIDGESTONE","DUELER H/L 422 ECOPIA","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HL422_ECOPIA.jpg"),
("BRIDGESTONE","TURANZA EL42","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_EL42_RFT.jpg"),
("BFGOODRICH","ALL TERRAIN T/A KO2","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_All_terrain_T_A_KO2.jpg"),
("BFGOODRICH","G-FORCE COMP-2 A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_G_FORCE_COMP_2_AS.jpg"),
("MICHELIN","PRIMACY 3","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PRIMACY_3.jpg"),
("BRIDGESTONE","BLIZZAK WS-80","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_WS80.jpg"),
("MICHELIN","LATITUDE TOUR HP","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_TOUR_HP.jpg"),
("BFGOODRICH","G-FORCE SPORT COMP-2","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_G_FORCE_SPORT_COMP_2.jpg"),
("BFGOODRICH","COMMERCIAL T/A A/S 2","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_COMMERCIAL_TA_ALL_SEASON_2.jpg"),
("BFGOODRICH","MUD TERRAIN T/A KM2","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_MUD_TERRAIN_TA_KM2.jpg"),
("MICHELIN","PILOT ALPIN PA4 ZP","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_ALPIN_PA4.jpg"),
("MICHELIN","X-ICE XI3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_X_ICE_XI3.jpg"),
("MICHELIN","LATITUDE SPORT 3","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_SPORT_3.jpg"),
("MICHELIN","PRIMACY MXV4","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PRIMACY_MXV4.jpg"),
("MICHELIN","PILOT SPORT 3","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_3.jpg"),
("MICHELIN","PRIMACY MXM4","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PRIMACY_MXM4_ZP.jpg"),
("MICHELIN","PILOT SUPER SPORT ZP","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SUPER_SPORT.jpg"),
("MICHELIN","PREMIER A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PREMIER_AS.jpg"),
("MICHELIN","PRIMACY 3 ZP","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PRIMACY_3.jpg"),
("MICHELIN","PILOT HX MXM4","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_HX_MXM4.jpg"),
("MICHELIN","LATITUDE SPORT 3 ZP","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_SPORT_3.jpg"),
("BRIDGESTONE","DUELER H/T D689","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HT_689.jpg"),
("CONTINENTAL","WINTERCONTACT SI","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_WINTERCONTACT_SI.JPG"),
("MICHELIN","ENERGY SAVER A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_ENERGY_SAVER_AS.jpg"),
("GISLAVED","NORDFROST 200","Y","N","","W","http://blobs.gislaved-tyres.com/www8/servlet/image/1042922/uncropped/0/560/4/nordfrost-200-product-picture-4.png"),
("GISLAVED","NORDFROST 200 STUDDED","Y","N","","W","http://blobs.gislaved-tyres.com/www8/servlet/image/1042922/uncropped/0/560/4/nordfrost-200-product-picture-4.png"),
("CONTINENTAL","CONTIPROCONTACT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT.jpg"),
("CONTINENTAL","CONTIPROCONTACT SSR","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT.jpg"),
("CONTINENTAL","CONTIPROCONTACT CONTISEAL","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 2","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_2.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 5 SSR","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_5_SSR.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 5P","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_5P.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 5","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_5.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 5 CSi","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_5.jpg"),
("CONTINENTAL","CONTIECOCONTACT EP","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIECOCONTACT_EP.jpg"),
("CONTINENTAL","CONTITOURINGCONTACT CV95","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTITOURINGCONTACT_CV95.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 5P SSR","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_5PSSR.jpg"),
("CONTINENTAL","CONTIWINTERCONTACT TS830P","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIWINTERCONTACT_TS830P.jpg"),
("CONTINENTAL","CONTIWINTERCONTACT TS830P SSR","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIWINTERCONTACT_TS830P_SSR.jpg"),
("CONTINENTAL","CONTIWINTERCONTACT TS800","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIWINTERCONTACT_TS800.jpg"),
("CONTINENTAL","CONTIWINTERCONTACT TS850P","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_WINTERCONTACT_TS850P.JPG"),
("CONTINENTAL","CONTI4X4CONTACT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_4X4CONTACT.jpg"),
("CONTINENTAL","CONTICROSSCONTACT WINTER","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CROSSCONTACTWINTER.jpg"),
("CONTINENTAL","CONTICROSSCONTACT UHP","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTICROSSCONTACT_UHP.jpg"),
("CONTINENTAL","CONTICROSSCONTACT LX SPORT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTICROSSCONTACT_LX_SPORT.jpg"),
("CONTINENTAL","CONTICROSSCONTACT LX SPORT SSR","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTICROSSCONTACT_LX_SPORT.jpg"),
("CONTINENTAL","CONTICROSSCONTACT LX SPORT CSi","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTICROSSCONTACT_LX_SPORT.jpg"),
("CONTINENTAL","CONTIPROCONTACT TX","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT_TX.jpg"),
("CONTINENTAL","CONTI4X4WINTERCONTACT SSR","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTI4X4XWINTERCONTACT_SSR.jpg"),
("CONTINENTAL","CONTI4X4SPORTCONTACT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_4X4SPORTCONTACT.jpg"),
("CONTINENTAL","CONTI4X4WINTERCONTACT","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTI4X4XWINTERCONTACT.jpg"),
("CONTINENTAL","CONTI4X4CONTACT SSR","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_4X4CONTACT_SSR.jpg"),
("CONTINENTAL","CONTICROSSCONTACT UHP SSR","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTICROSSCONTACT_UHP_SSR.jpg"),
("CONTINENTAL","CONTICROSSCONTACT LX","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTICROSSCONTACT_LX.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 3","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_3.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 5P CSi","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_5P.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 2 SSR","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_2_SSR.jpg"),
("CONTINENTAL","CONTISPORTCONTACT 3 SSR","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTISPORTCONTACT_3_SSR.jpg"),
("CONTINENTAL","CONTIPROCONTACT TX SSR","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT_TX_SSR.jpg"),
("CONTINENTAL","CONTIPROCONTACT GX SSR","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT_GX_SSR.jpg"),
("CONTINENTAL","CONTIPREMIUMCONTACT 2 SSR","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPREMIUMCONTACT2.jpg"),
("CONTINENTAL","CONTIPREMIUMCONTACT 2","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPREMIUMCONTACT2.jpg"),
("CONTINENTAL","CONTIPROCONTACT TX CSi","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT_TX.jpg"),
("CONTINENTAL","CONTIPROCONTACT GX","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTIPROCONTACT_GX.jpg"),
("MICHELIN","LATITUDE ALPIN LA2","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_ALPIN_LA2.jpg"),
("BFGOODRICH","RADIAL T/A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_RADIAL_TA_SPEC.jpg"),
("MICHELIN","LTX A/T2","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LTX_AT_2.jpg"),
("MICHELIN","LATITUDE TOUR","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_TOUR.jpg"),
("BRIDGESTONE","BLIZZAK LM-25 RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_LM_25_RFT.jpg"),
("CONTINENTAL","CONTITRAC TR","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTITRAC_TR.jpg"),
("CONTINENTAL","CONTITRAC","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTITRAC.jpg"),
("FIRESTONE","FIREHAWK GTA-03","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_FIREHAWK_GTA_03.jpg"),
("MICHELIN","LATITUDE SPORT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_SPORT.jpg"),
("GENERAL","GRABBER HTS","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GENERAL/GENERAL_GRABBER_HTS.jpg"),
("GENERAL","AMERITRAC TR","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GENERAL/GENERAL_AMERITRAC_TR.jpg"),
("GENERAL","AMERITRAC","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GENERAL/GENERAL_AMERITRAC.jpg"),
("BFGOODRICH","RUGGED TRAIL T/A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_RUGGED_TRAIL_TA.jpg"),
("CONTINENTAL","VANCO FOURSEASON","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_VANCOFOURSEASON.jpg"),
("CONTINENTAL","VANCO 2","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_VANCO2.jpg"),
("CONTINENTAL","VANCOCONTACT WINTER","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/CONTI/CONTINENTAL VANCO WINTERCONTACT.jpg"),
("MICHELIN","PRIMACY HP","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PRIMACY_HP.jpg"),
("MICHELIN","X-ICE XI3 ZP","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_X_ICE_XI3.jpg"),
("MICHELIN","PILOT SPORT PS2","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_PS2.jpg"),
("MICHELIN","PILOT SPORT 3 ZP","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_3.jpg"),
("MICHELIN","LTX A/S NT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LTX_AS.jpg"),
("BRIDGESTONE","POTENZA RE050A II RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE050A_II_RFT.jpg"),
("MICHELIN","LTX A/T2 DT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LTX_AT_2.jpg"),
("BRIDGESTONE","POTENZA RE92","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE92.jpg"),
("PIRELLI","PZERO ASIMMETRICO","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_ASIMMETRICO.jpg"),
("MICHELIN","PILOT SPORT CUP 2 ZP","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_CUP_2.jpg"),
("MICHELIN","LTX M/S2","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LTX_MS_2.jpg"),
("BRIDGESTONE","POTENZA S02A","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_S_02A.jpg"),
("PIRELLI","PZERO DIREZIONALE","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/4S/PIRELLI/PZERO ASIMMETRICO.jpg"),
("MICHELIN","LATITUDE TOUR HP ZP","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_TOUR_HP_ZP.jpg"),
("BRIDGESTONE","BLIZZAK LM-25 4X4 RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_LM_25_4X4_RFT.jpg"),
("PIRELLI","PZERO ROSSO ASIMMETRICO","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_ROSSO_ASIMMETRICO.jpg"),
("HANKOOK","DYNAPRO AT RF08","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_RF08.jpg"),
("HANKOOK","OPTIMO H725","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H725.jpg"),
("HANKOOK","OPTIMO H725A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H725A.jpg"),
("HANKOOK","VENTUS V12 EVO K110","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_K110.jpg"),
("HANKOOK","WINTER I-PIKE RW11","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_RW11.jpg"),
("HANKOOK","VENTUS V4 ES H105","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H105_H105_OE.jpg"),
("HANKOOK","OPTIMO H428","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H428.jpg"),
("GT RADIAL","CHAMPIRO ICEPRO 2","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_ICEPRO_2.jpg"),
("GT RADIAL","SAVERO HT2","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_SAVERO_HT2.jpg"),
("GT RADIAL","CHAMPIRO UHP1","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_UHP1.jpg"),
("GT RADIAL","CHAMPIRO ICEPRO","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_ICEPRO.jpg"),
("GT RADIAL","CHAMPIRO VP1","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_VP1.jpg"),
("GT RADIAL","CHAMPIRO ICEPRO SUV","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_ICEPRO_SUV.jpg"),
("GT RADIAL","ADVENTURO M/T","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_ADVENTURO_MT.jpg"),
("GT RADIAL","ADVENTURO AT3","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_ADVENTURO_AT3.jpg"),
("GT RADIAL","CHAMPIRO UHP AS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_UHP_AS.jpg"),
("GT RADIAL","CHAMPIRO WINTERPRO","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_WINTERPRO.jpg"),
("GT RADIAL","CHAMPIRO WINTERPRO HP","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_WINTERPRO_HP.jpg"),
("GT RADIAL","SAVERO WT","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_SAVERO_WT.jpg"),
("GT RADIAL","MAXMILER WT-1000","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_MAXMILER_WT_1000.jpg"),
("GT RADIAL","MAXTOUR 70","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_MAXTOUR.jpg"),
("HANKOOK","OPTIMO H426","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H426_H426_OE.jpg"),
("HANKOOK","VENTUS PRIME 2 K115","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_K115.jpg"),
("HANKOOK","DYNAPRO HT RH12","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_RH12.jpg"),
("HANKOOK","DYNAPRO HP2 RA33","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_RA33.jpg"),
("HANKOOK","WINTER I-PIKE W409","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_W409.jpg"),
("HANKOOK","VENTUS S1 EVO2 SUV K117A","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_K117.jpg"),
("HANKOOK","VENTUS S1 EVO2 K117","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_K117.jpg"),
("HANKOOK","DYNAPRO AT-M RF10 4S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_RF10.jpg"),
("HANKOOK","VENTUS S1 EVO2 K117B","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_K117.jpg"),
("HANKOOK","VENTUS S1 NOBLE2 H452","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H452.jpg"),
("HANKOOK","WINTER I-PIKE RS W419","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_W419.jpg"),
("HANKOOK","VENTUS V12 EVO2 K120","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_K120.jpg"),
("HANKOOK","OPTIMO H724 A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H724.jpg"),
("HANKOOK","DYNAPRO AT-M RF10","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TREAD/HANKOOK/DYNAPRO_AT_MRF10.jpg"),
("HANKOOK","VENTUS V2 CONCEPT2 H457","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_H457.jpg"),
("TOYO","OBSERVE GSi-5","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OBSERVE_GSI5.jpg"),
("GOODYEAR","EAGLE F1 ASYM A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYM_AS.jpg"),
("YOKOHAMA","ADVAN SPORT V105","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_ADVAN_SPORT_V105.jpg"),
("BFGOODRICH","KRAWLER T/A KX","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_KRAWLER_TA_KX.jpg"),
("GOODYEAR","EAGLE GT II","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_GT_II.jpg"),
("GOODYEAR","EAGLE RS-A2","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_RS_A2.jpg"),
("GOODYEAR","EAGLE SPORT A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_SPORT_AS.jpg"),
("GOODYEAR","EAGLE SPORT A/S ROF","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_SPORT_AS.jpg"),
("YOKOHAMA","PARADA SPEC X PA02","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_PARADA_SPEC_X.jpg"),
("YOKOHAMA","ADVAN A048","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_A048.jpg"),
("YOKOHAMA","GEOLANDAR G055","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_GEOLANDAR_SUVCUV_G055.jpg"),
("YOKOHAMA","GEOLANDAR I/T G072","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_GEOLANDAR_IT_G072.jpg"),
("YOKOHAMA","ADVAN NEOVA AD08R","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_ADVAN_NEOVA_AD08R.jpg"),
("YOKOHAMA","ADVAN SPORT V103","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_ADVAN_SPORT.jpg"),
("TOYO","OBSERVE G3-ICE","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OBSERVE_G3_ICE.jpg"),
("YOKOHAMA","AVID TOURING S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_AVID_TOURING_S.jpg"),
("YOKOHAMA","AVID ASCEND","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_AVID_ASCEND.jpg"),
("YOKOHAMA","AVID S33B","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_AVID_S33.jpg"),
("YOKOHAMA","AVID C33","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_AVID_C33.jpg"),
("YOKOHAMA","AVID S33D","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_AVID_S33.jpg"),
("YOKOHAMA","ICEGUARD IG51V","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_IG51V.jpg"),
("YOKOHAMA","ADVAN ST V802","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_ADVAN_ST.jpg"),
("YOKOHAMA","AVID S34B","N","N","","4S",""),
("YOKOHAMA","ADVAN A11A","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_ADVAN_A11A.jpg"),
("YOKOHAMA","AVID S34D","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_AVID_S34D.jpg"),
("YOKOHAMA","GEOLANDAR G96B","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_G96B.jpg"),
("YOKOHAMA","AVID S34F","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_AVID_S34F.jpg"),
("YOKOHAMA","GEOLANDAR G91F","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_G91F.jpg"),
("NEXEN","WINGUARD SPORT","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_WINGUARD_SPORT.jpg"),
("NEXEN","CP662","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_CP662.jpg"),
("GOODYEAR","EXCELLENCE ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EXCELLENCE_ROF.jpg"),
("GOODYEAR","EFFICIENT GRIP ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EFFICIENT_GRIP_ROF.jpg"),
("GOODYEAR","EFFICIENT GRIP","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EFFICIENT_GRIP.jpg"),
("GOODYEAR","EFFICIENT GRIP SUV 4X4","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EFFICIENT_GRIP.jpg"),
("TOYO","VERSADO ECO","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_VERSADO_ECO.jpg"),
("FIRESTONE","WINTERFORCE","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/FIRESTONE/FIRESTONE_WINTERFORCE.jpg"),
("NEXEN","CP671","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_CP671.jpg"),
("BFGOODRICH","RADIAL T/A SPEC","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_RADIAL_TA_SPEC.jpg"),
("NEXEN","ROADIAN HTX RH5","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_ROADIAN_HTX_RH5.jpg"),
("GOODYEAR","ULTRA GRIP PERFORMANCE 2 RSC","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ULTRA_GRIP_PERFORMANCE2.jpg"),
("MICHELIN","PRIMACY MXM4 ZP","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PRIMACY_MXM4_ZP.jpg"),
("BRIDGESTONE","POTENZA RE050 RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE050_RFT.jpg"),
("BRIDGESTONE","TURANZA EL400 RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_TURANZA_EL400_RFT.jpg"),
("NEXEN","NFERA RU5","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NFERA_RU5.jpg"),
("BRIDGESTONE","DUELER H/P 92A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DUELER_HP_92A.jpg"),
("BRIDGESTONE","POTENZA RE070R RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE070R_RFT.jpg"),
("NEXEN","ROADIAN AT PRO RA8 A/S","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_ROADIAN_AT_PRO_RA8.jpg"),
("NEXEN","ROADIAN AT PRO RA8","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_ROADIAN_AT_PRO_RA8.jpg"),
("NEXEN","NPRIZ RH7","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_NPRIZ_RH7.jpg"),
("TOYO","CELSIUS","N","Y","","WS","https://toyotires-1524598101.netdna-ssl.com/media/1091/ce.png"),
("BRIDGESTONE","BLIZZAK LM-60 RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_LM_60_RFT.jpg"),
("BRIDGESTONE","POTENZA RE92A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE92A.jpg"),
("TOYO","VERSADO NOIR","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_VERSADO_NOIR.jpg"),
("NEXEN","NPRIZ AH8","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_NPRIZ_AH8.jpg"),
("PIRELLI","SCORPION STR","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_STR.jpg"),
("YOKOHAMA","Y788R","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/YOKOHAMA/YOKOHAMA_Y788R_OE.jpg"),
("TOYO","A20","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_A20.jpg"),
("TOYO","A22","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_A22.jpg"),
("TOYO","A24A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_A24A.jpg"),
("BRIDGESTONE","POTENZA RE050A I RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE050A_I_RFT.jpg"),
("NEXEN","WINGUARD WINSPIKE 62","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/NEXEN/NEXEN_WINSPIKE.jpg"),
("PIRELLI","SCORPION ZERO","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_ZERO.jpg"),
("PIRELLI","PZERO NERO","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_NERO.jpg"),
("TOYO","PROXES R1R","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_PROXES_R1R.jpg"),
("BRIDGESTONE","POTENZA RE960AS PP RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_POTENZA_RE960AS_PP_RFT.jpg"),
("PIRELLI","PZERO ROSSO DIREZIONALE","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_ROSSO_DIREZIONALE.jpg"),
("MICHELIN","ENERGY SAVER","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_ENERGY_SAVER.jpg"),
("MICHELIN","LTX WINTER","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LTX_WINTER.jpg"),
("TOYO","EXTENSA A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_EXTENSA_AS.jpg"),
("PIRELLI","SCORPION ZERO ASIMMETRICO","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_ZERO_ASIMMETRICO_RFT.jpg"),
("PIRELLI","PZERO CORSA DIREZIONALE","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_CORSA_DIREZIONALE.jpg"),
("GOODYEAR","WRANGLER DURATRAC","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_DURATRAC.jpg"),
("BRIDGESTONE","BLIZZAK W965","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_BLIZZAK_W965.jpg"),
("GOODYEAR","FORTERA HL","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_FORTERA_HL.jpg"),
("GOODYEAR","FORTERA SL","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_FORTERA_SL.jpg"),
("MICHELIN","LATITUDE ALPIN LA2 ZP","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_ALPIN_LA2.jpg"),
("TOYO","PROXES A18","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_PROXES_A18.jpg"),
("CONTINENTAL","EXTREMECONTACT DW","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_EXTREMECONTACT_DW.jpg"),
("CONTINENTAL","CONTICROSSCONTACT LX20","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_CONTICROSSCONTACT_LX20.jpg"),
("GENERAL","ALTIMAX RT43","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GENERAL/GENERAL_ALTIMAX_RT43.jpg"),
("CONTINENTAL","PURECONTACT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/CONTINENTAL/CONTINENTAL_PURECONTACT.jpg"),
("GENERAL","ALTIMAX ARCTIC","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GENERAL/GENERAL_ALTIMAX_ARCTIC.jpg"),
("GOODYEAR","WRANGLER FORTITUDE HT","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_FORTITUDE_HT.jpg"),
("PIRELLI","SCORPION STR A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_STR.jpg"),
("PIRELLI","W240 SOTTOZERO","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_240_SOTTOZERO.jpg"),
("MICHELIN","PILOT SPORT PS2 ZP","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_PS2_ZP.jpg"),
("PIRELLI","PZERO CORSA ASIMMETRICO","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_CORSA_ASIMMETRICO.jpg"),
("PIRELLI","SCORPION ATR","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_ATR.jpg"),
("PIRELLI","SCORPION ICE & SNOW","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_ICE_SNOW.jpg"),
("TOYO","OPEN COUNTRY H/T","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_HT.jpg"),
("PIRELLI","PZERO","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO.jpg"),
("KUMHO","ECSTA KL12 UHP","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_ECSTA_KL12_UHP.jpg"),
("PIRELLI","PZERO NERO ALL SEASON","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_NERO_ALL_SEASON.jpg"),
("GOODYEAR","EAGLE ULTRA GRIP GW3 EMT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_ULTRA_GRIP_GW3_ROF.jpg"),
("GOODYEAR","EAGLE ULTRA GRIP GW3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_ULTRA_GRIP_GW3.jpg"),
("TOYO","OPEN COUNTRY WLT1","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_WLT1.jpg"),
("PIRELLI","PZERO RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO.jpg"),
("KUMHO","ROAD VENTURE MT KL71","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_ROAD_VENTURE_MT_KL71.jpg"),
("TOYO","PROXES T1 SPORT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_PROXES_T1_SPORT.jpg"),
("TOYO","PROXES 4 PLUS A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_PROXES_4_PLUS.jpg"),
("PIRELLI","SCORPION ZERO ASIMMETRICO WS","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_ZERO_ASIMMETRICO.jpg"),
("GOODYEAR","WRANGLER SR-A","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_SR_A.jpg"),
("PIRELLI","SCORPION VERDE ALL SEASON","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_VERDE_ALL_SEASON_RFT.jpg"),
("PIRELLI","W270 SOTTOZERO SERIE II","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_270_SOTTOZERO_SERIE_II.jpg"),
("PIRELLI","W210 SOTTOZERO SERIE II","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_210_SOTTOZERO_SERIE_II_RFT.jpg"),
("PIRELLI","W240 SOTTOZERO SERIE II","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_240_SOTTOZERO_SERIE_II.jpg"),
("PIRELLI","W210 SOTTOZERO","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_210_SOTTOZERO.jpg"),
("PIRELLI","CINTURATO P7","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_CINTURATO_P7.jpg"),
("PIRELLI","W240 SOTTOZERO SERIE II RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_240_SOTTOZERO_SERIE_II_RFT.jpg"),
("PIRELLI","W210 SOTTOZERO SERIE II RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_210_SOTTOZERO_SERIE_II_RFT.jpg"),
("PIRELLI","SCORPION VERDE","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_VERDE_RFT.jpg"),
("BRIDGESTONE","DURAVIS R500 HD","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DURAVIS_R500_HD.jpg"),
("PIRELLI","CINTURATO P1","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_CINTURATO_P1.jpg"),
("TOYO","PROXES 4","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_PROXES_4.jpg"),
("PIRELLI","CINTURATO P7 RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_CINTURATO_P7_RFT.jpg"),
("PIRELLI","CINTURATO P7 ALL SEASON","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_CINTURATO_P7_ALL_SEASON.jpg"),
("HANKOOK","DYNAPRO AS RH03","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/HANKOOK/HANKOOK_RH03.jpg"),
("ROVELO","RWS-677","Y","N","","W","http://static.ak24.ee/img_prd/358/358561/rws-677_rovelo.jpg"),
("ROVELO","RWS-677 STUDDED","Y","N","","W","http://static.ak24.ee/img_prd/358/358561/rws-677_rovelo.jpg"),
("PIRELLI","CINTURATO P7 ALL SEASON RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_CINTURATO_P7_ALL_SEASON_RFT.jpg"),
("BRIDGESTONE","DURAVIS M700 HD","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BRIDGESTONE/BRIDGESTONE_DURAVIS_M700_HD.jpg"),
("KUMHO","SOLUS KH16","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_SOLUS_KH16.jpg"),
("KUMHO","SOLUS KL21 ECO","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_SOLUS_KL21_ECO.jpg"),
("KUMHO","SOLUS KL21","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_SOLUS_KL21_ECO.jpg"),
("PIRELLI","W190 SNOWCONTROL SERIE 3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_190_SNOWCONTROL_SERIE_3.jpg"),
("KUMHO","SOLUS KH25","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_SOLUS_KH25.jpg"),
("KUMHO","ROAD VENTURE APT KL51","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_ROAD_VENTURE_APT_KL51.jpg"),
("KUMHO","I'ZEN RV KC15","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_I_ZEN_RV_KC15.jpg"),
("KUMHO","POWER GRIP KC11","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_POWER_GRIP_KC11.jpg"),
("KUMHO","CRUGEN PREMIUM KL33","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_CITY_VENTURE_COMFORT_KL33.jpg"),
("KUMHO","I'ZEN KW31","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_I_ZEN_KW31.jpg"),
("KUMHO","SOLUS TA31","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_SOLUS_TA31.jpg"),
("KUMHO","SOLUS HA31","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_SOLUS_HA31.jpg"),
("PIRELLI","SCORPION WINTER","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_WINTER_RFT.jpg"),
("PIRELLI","WINTER SOTTOZERO 3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TREAD/PIRELLI/WINTER_SOTTOZERO_3.JPG"),
("KUMHO","SOLUS HA31 SUV","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KUMHO/KUMHO_SOLUS_HA31.jpg"),
("PIRELLI","WINTER SOTTOZERO 3 RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_WINTER_SOTTOZERO_3_RFT.jpg"),
("PIRELLI","CINTURATO P7 ALL SEASON PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_CINTURATO_P7_ALL_SEASON_PLUS.jpg"),
("PIRELLI","SCORPION WINTER RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_WINTER_RFT.jpg"),
("PIRELLI","W210 SNOWCONTROL SERIE 3 RFT","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_210_SNOWCONTROL_SERIE_3_RFT.jpg"),
("MICHELIN","PILOT SPORT A/S 3","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_AS_3.jpg"),
("PIRELLI","W210 SNOWCONTROL SERIE 3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_W_210_SNOWCONTROL_SERIE_3.jpg"),
("PIRELLI","PZERO NERO GT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_NERO_GT.jpg"),
("PIRELLI","PZERO PZ4 LUXURY RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_PZ4.jpg"),
("PIRELLI","SCORPION VERDE ALL SEASON RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_VERDE_ALL_SEASON_RFT.jpg"),
("PIRELLI","PZERO NERO ALL SEASON RFT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_NERO_ALL_SEASON_RFT.jpg"),
("PIRELLI","PZERO PZ4 SPORT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_PZ4.jpg"),
("PIRELLI","PZERO ALL SEASON PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_ALL_SEASON_PLUS.jpg"),
("PIRELLI","SCORPION VERDE ALL SEASON PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_VERDE_ALL_SEASON_PLUS.jpg"),
("PIRELLI","SCORPION VERDE ALL SEASON NCS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_VERDE_ALL_SEASON_RFT.jpg"),
("PIRELLI","PZERO ALL SEASON","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_ALL_SEASON_PLUS.jpg"),
("PIRELLI","SCORPION VERDE RFT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_VERDE.jpg"),
("PIRELLI","P4 FOUR SEASONS PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_P4_FOUR_SEASONS_PLUS.jpg"),
("PIRELLI","PZERO CORSA PZC4","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_CORSA_DIREZIONALE.jpg"),
("PIRELLI","PZERO PZ4 LUXURY","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_PZ4.jpg"),
("TOYO","PROXES 4 PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_PROXES_4_PLUS.jpg"),
("DUNLOP","SP SPORT MAXX TT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_TT.jpg"),
("DUNLOP","SP SPORT MAXX TT DSST","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_TT_DSST.jpg"),
("DUNLOP","SIGNATURE HP","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SIGNATURE_HP.jpg"),
("DUNLOP","SP WINTER SPORT M3 DSST","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_WINTER_SPORT_M3_DSST.jpg"),
("DUNLOP","SP WINTER SPORT M3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_WINTER_SPORT_M3.jpg"),
("DUNLOP","SP SPORT 7000 A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_7000_AS.jpg"),
("DUNLOP","SP SPORT 4000 DSST","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_4000_DSST.jpg"),
("DUNLOP","SP SPORT 5000M","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_5000_SYMMETRICAL.jpg"),
("DUNLOP","SP SPORT 5000","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_5000_SYMMETRICAL.jpg"),
("DUNLOP","SP SPORT 01A","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_01A.jpg"),
("DUNLOP","SP SPORT 5000 DSST","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_5000_DSST_CTT.jpg"),
("DUNLOP","SP SPORT 5000M DSST","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_5000_DSST_CTT.jpg"),
("DUNLOP","SP SPORT 01","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_01.jpg"),
("DUNLOP","SPORT MAXX RT NST","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_RT.jpg"),
("DUNLOP","SP SPORT 01 DSST","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_01_DSST.jpg"),
("DUNLOP","SP SPORT 600","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_600.jpg"),
("DUNLOP","SP SPORT MAXX GT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_GT.jpg"),
("DUNLOP","SP SPORT MAXX","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX.jpg"),
("DUNLOP","SP SPORT MAXX A","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX.jpg"),
("DUNLOP","SP SPORT MAXX GT DSST","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_GT_ROF.jpg"),
("DUNLOP","SP SPORT MAXX 050","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX.jpg"),
("DUNLOP","SP SPORT MAXX 050 DSST","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_050_DSST.jpg"),
("DUNLOP","SP SPORT 2050","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_2050.jpg"),
("DUNLOP","SP WINTER SPORT 3D","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_WINTER_SPORT_3D.jpg"),
("DUNLOP","SP WINTER SPORT 3D DSST","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_WINTER_SPORT_3D_DSST.jpg"),
("DUNLOP","SP SPORT MAXX DSST","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_DSST.jpg"),
("DUNLOP","SP SPORT MAXX GT ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_GT_ROF.jpg"),
("DUNLOP","SP SPORT MAXX GT600 DSST","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_GT_600_DSST.jpg"),
("DUNLOP","SPORT MAXX RACE","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_RACE.jpg"),
("DUNLOP","WINTER SPORT 4D","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_WINTER_SPORT_4D.jpg"),
("DUNLOP","WINTER SPORT 4D DSST","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_WINTER_SPORT_4D_DSST_ROF.jpg"),
("DUNLOP","WINTER SPORT 4D ROF","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_WINTER_SPORT_4D_DSST_ROF.jpg"),
("DUNLOP","SPORT MAXX RT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_RT.jpg"),
("DUNLOP","SPORT MAXX RT ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_RT.jpg"),
("DUNLOP","DIREZZA DZ102","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_DIREZZA_DZ102.jpg"),
("DUNLOP","SP SPORT 5000 SYMMETRIC","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_5000_SYMMETRICAL.jpg"),
("DUNLOP","SP SPORT 7010 A/S DSST","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_7010_AS_DSST.jpg"),
("DUNLOP","SP SPORT MAXX A1 A/S","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX.jpg"),
("DUNLOP","SP SPORT MAXX 101","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX.jpg"),
("DUNLOP","SP SPORT MAXX A1-A A/S","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX.jpg"),
("DUNLOP","SP SPORT MAXX GT NST","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SP_SPORT_MAXX_GT.jpg"),
("DUNLOP","SIGNATURE II","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SIGNATURE_II.jpg"),
("DUNLOP","WINTER MAXX","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_WINTER_MAXX.jpg"),
("DUNLOP","WINTER MAXX DSST","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_WINTER_MAXX.jpg"),
("GOODYEAR","ULTRA GRIP ICE WRT LT","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ULTRAGRIP_ICE_WRT_LT.jpg"),
("PIRELLI","SCORPION ZERO ALL SEASON","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_SCORPION_VERDE_ALL_SEASON_RFT.jpg"),
("MICHELIN","PILOT SPORT A/S PLUS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_AS_PLUS.jpg"),
("PIRELLI","CINTURATO P7 ALL SEASON NCS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TREAD/PIRELLI/CINTURATO_P7_ALL_SEASON_RFT.jpg"),
("PIRELLI","PZERO PZ4 SPORT NCS","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/PIRELLI/PIRELLI_PZERO_PZ4.jpg"),
("DUNLOP","GRANDTREK AT21","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_AT21.jpg"),
("DUNLOP","GRANDTREK AT23","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_AT23.jpg"),
("DUNLOP","GRANDTREK AT20","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_AT20.jpg"),
("DUNLOP","SIGNATURE CS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_SIGNATURE_CS.jpg"),
("DUNLOP","GRANDTREK WT M3 DSST","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_WT_M3_ROF.jpg"),
("DUNLOP","GRANDTREK PT2A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_PT2A.jpg"),
("DUNLOP","GRANDTREK TOURING A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_TOURING_AS.jpg"),
("DUNLOP","GRANDTREK SJ6","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_SJ6.jpg"),
("DUNLOP","GRANDTREK ST30","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_ST30.jpg"),
("DUNLOP","GRANDTREK ST20","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_ST20.jpg"),
("DUNLOP","GRANDTREK WT M3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/DUNLOP/DUNLOP_GRANDTREK_WT_M3.jpg"),
("TOYO","OPEN COUNTRY A20","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_A20.jpg"),
("TOYO","OPEN COUNTRY A20A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_A20.jpg"),
("TOYO","M-55 4S","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_M_55.jpg"),
("TOYO","OPEN COUNTRY A25A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_A25.jpg"),
("TOYO","OPEN COUNTRY A20B","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_A20.jpg"),
("GOODYEAR","WRANGLER DURATRAC LT","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_DURATRAC.jpg"),
("TOYO","M-55","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_M_55.jpg"),
("TOYO","OPEN COUNTRY CT","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_CT.jpg"),
("TOYO","OPEN COUNTRY A/TII 4S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_ATII.jpg"),
("TOYO","OPEN COUNTRY A/TII XTREME","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_ATII.jpg"),
("KELLY","SAFARI TSR","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/KELLY/KELLY_SAFARI_TSR.jpg"),
("GOODYEAR","FIERCE ATTITUDE M/T","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_FIERCE_ATTITUDE_MT.jpg"),
("TOYO","OPEN COUNTRY M/T","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_MT.jpg"),
("TOYO","OPEN COUNTRY H/T TUFF DUTY","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/TOYO/TOYO_OPEN_COUNTRY_HT_TUFF_DUTY.jpg"),
("MICHELIN","LATITUDE X-ICE XI2 ZP","Y","N","Y","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_X_ICE_XI2_ZP.jpg"),
("MICHELIN","4X4 DIAMARIS","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_4X4_DIAMARIS.jpg"),
("GOODYEAR","EAGLE F1 SUPERCAR","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_SUPERCAR.jpg"),
("GOODYEAR","ASSURANCE TRIPLETRED A/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ASSURANCE_TRIPLETRED_ALL_SEASON.jpg"),
("GOODYEAR","INTEGRITY","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_INTEGRITY.jpg"),
("GOODYEAR","WRANGLER HP","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_HP.jpg"),
("GOODYEAR","EAGLE F1 GS EMT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_GS_EMT.jpg"),
("GOODYEAR","EAGLE F1 GS-2 EMT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_GS_2_EMT.jpg"),
("GOODYEAR","ASSURANCE ALL-SEASON","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ASSURANCE_ALL_SEASON.jpg"),
("GOODYEAR","EAGLE F1 SUPERCAR G 2","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_SUPERCAR_G2.jpg"),
("GOODYEAR","EAGLE F1 SUPERCAR G 2 ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_SUPERCAR_G2_ROF.jpg"),
("GOODYEAR","WRANGLER AT/S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_ATS.jpg"),
("GOODYEAR","EAGLE F1 SUPERCAR EMT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_SUPERCAR_EMT.jpg"),
("GOODYEAR","ASSURANCE COMFORTRED TOURING","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ASSURANCE_COMFORTRED_TOURING.jpg"),
("GOODYEAR","ASSURANCE COMFORTRED","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ASSURANCE_COMFORTRED.jpg"),
("UNIROYAL","LAREDO CROSS COUNTRY","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/UNIROYAL/UNIROYAL_LAREDO_CROSS_COUNTRY.jpg"),
("UNIROYAL","LAREDO HD/T","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/UNIROYAL/UNIROYAL_LAREDO_HDT.jpg"),
("GOODYEAR","EAGLE RS-A EMT","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_RS_A_EMT.jpg"),
("BFGOODRICH","COMMERCIAL T/A TRACTION","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/BF_GOODRICH/BF_GOODRICH_COMMERCIAL_TA_TRACTION.jpg"),
("MICHELIN","LATITUDE ALPIN","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_LATITUDE_ALPIN.jpg"),
("GOODYEAR","EXCELLENCE","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EXCELLENCE.jpg"),
("GOODYEAR","EAGLE LS-2","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_LS2.jpg"),
("GOODYEAR","EAGLE LS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_LS.jpg"),
("GOODYEAR","EAGLE LS-2 ROF","N","N","Y","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_LS2_ROF.jpg"),
("GOODYEAR","EAGLE F1 GS D3","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_GS_D3.jpg"),
("GOODYEAR","WRANGLER HP ALL WEATHER","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_HP_ALL_WEATHER.jpg"),
("GOODYEAR","EAGLE RS-A POLICE","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_RS_A_POLICE.jpg"),
("GOODYEAR","EAGLE RS-A","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_RS_A.jpg"),
("GOODYEAR","ASSURANCE FUEL MAX","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ASSURANCE_FUEL_MAX.jpg"),
("GOODYEAR","WRANGLER ARMORTRAC","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_ARMORTRAC.jpg"),
("GOODYEAR","WRANGLER MT","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_MT.jpg"),
("GOODYEAR","WRANGLER HT","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_HT.jpg"),
("GOODYEAR","ASSURANCE CS TRIPLETRED AS","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ASSURANCE_CS_TRIPLETRED_AS.jpg"),
("GOODYEAR","WRANGLER AT ADVENTURE","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_AT_ADVENTURE_LT.jpg"),
("GOODYEAR","WRANGLER AT ADVENTURE KEVLAR","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_AT_ADVENTURE_LT.jpg"),
("GOODYEAR","WRANGLER SILENT ARMOR","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_SILENT_ARMOR.jpg"),
("GOODYEAR","WRANGLER MT/R W/KEVLAR","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_MTR_WKEVLAR.jpg"),
("GOODYEAR","MILITARY WRANGLER MT/R","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_MILITARY_WRANGLER_MTR.jpg"),
("GOODYEAR","ULTRA GRIP+ SUV 4X4","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ULTRAGRIP_PLUS_SUV_4X4.jpg"),
("GOODYEAR","ULTRA GRIP ICE WRT","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ULTRAGRIP_ICE_WRT.jpg"),
("GOODYEAR","ASSURANCE CS FUEL MAX","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ASSURANCE_CS_FUEL_MAX.jpg"),
("GOODYEAR","ULTRA GRIP WINTER","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ULTRA_GRIP_WINTER.jpg"),
("GOODYEAR","CARGO ULTRAGRIP 2","Y","N","","WLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_CARGO_ULTRAGRIP_2.jpg"),
("GOODYEAR","WRANGLER ST","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_ST.jpg"),
("GOODYEAR","ULTRA GRIP ICE","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_ULTRA_GRIP_ICE.jpg"),
("GOODYEAR","EAGLE F1 ASYM","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYMMETRIC.jpg"),
("GOODYEAR","EAGLE F1 ASYM SUV A/T","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYMMETRIC_SUV.jpg"),
("GOODYEAR","EAGLE F1 ASYM 2 ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYM_2_ROF.jpg"),
("GOODYEAR","EAGLE F1 ASYM 2","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYM_2.jpg"),
("GOODYEAR","EAGLE F1 ASYM SUV","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYMMETRIC_SUV.jpg"),
("GOODYEAR","EAGLE F1 ASYM 2 ROF SCT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYM_2_ROF.jpg"),
("GOODYEAR","EAGLE F1 ASYM SUV A/T SCT","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYMMETRIC_SUV.jpg"),
("GOODYEAR","EAGLE F1 ASYM SUV ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_F1_ASYMMETRIC.jpg"),
("GOODYEAR","WRANGLER RADIAL","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_WRANGLER_RADIAL.jpg"),
("GOODYEAR","EAGLE NCT5 EMT","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_NCT5_ROF.jpg"),
("GOODYEAR","EAGLE NCT5 A ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_NCT5_ROF.jpg"),
("GOODYEAR","EAGLE NCT5 ROF","N","N","Y","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GOODYEAR/GOODYEAR_EAGLE_NCT5_ROF.jpg"),
("MICHELIN","AGILIS","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_AGILIS.jpg"),
("UNIROYAL","TIGER PAW TOURING","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/UNIROYAL/UNIROYAL_TIGER_PAW_TOURING.jpg"),
("MICHELIN","PILOT SPORT 4 S","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MICHELIN/MICHELIN_PILOT_SPORT_CUP_2.jpg"),
("GT RADIAL","CHAMPIRO HPY","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/GT_RADIAL/GT_RADIAL_CHAMPIRO_HPY.jpg"),
("MAXXIS","BIGHORN MT-762","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_BIGHORN MT-762.png"),
("MAXXIS","BRAVO AT-771 AW","N","Y","","WSLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_BRAVO AT-771.png"),
("MAXXIS","BRAVO AT-771","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_BRAVO AT-771.png"),
("MAXXIS","BRAVO HT-770","N","N","","SLT","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_BRAVO HT-770.png"),
("MAXXIS","NP3","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_NP3.png"),
("MAXXIS","NP3-PS STUDDED","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_NP3.png"),
("MAXXIS","PRESA SUV SS-01","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_PRESA SUV SS-01.png"),
("MAXXIS","BRAVO HP-M3","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_HP-M3.png"),
("MAXXIS","VICTRA MA-Z4S","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_VICTRA MA-Z4S.png"),
("MAXXIS","ESCAPADE MA-T1","N","N","","4S","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_ESCAPADE MA-T1.png"),
("MAXXIS","ARCTIC TREKKER SP-02","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_ARCTIC TREKKER SP-02.png"),
("MAXXIS","VICTRA SPORT VS-01","N","N","","SS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_VICTRA SPORT VS-01.png"),
("MAXXIS","AP2","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_AP2.png"),
("MAXXIS","MA-SAS","N","Y","","WS","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_MA-SAS.png"),
("MAXXIS","WP-05","Y","N","","W","http://www.touchettedistribution.com/WebOrder/Images/Images 2014/MAXXIS/MAXXIS_WP-05.jpg");